document.addEventListener("DOMContentLoaded",()=>{
cacheElements();
const backendStatus=document.createElement("span");backendStatus.className="backend-status";backendStatus.textContent=BackendSync.isConfigured()?"Cloud connected":"Local mode";backendStatus.id="backend-status";document.querySelector(".topbar-actions")?.prepend(backendStatus);
if(!localStorage.getItem(STORAGE_KEYS.tasks))saveTasks(DEFAULT_TASKS);
if(!localStorage.getItem(STORAGE_KEYS.team))saveTeam(DEFAULT_TEAM);
if(!localStorage.getItem(STORAGE_KEYS.activity))saveActivity([]);
if(!localStorage.getItem(STORAGE_KEYS.comments))saveComments({});
document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>b.dataset.role==="guest"?showWorkspace("guest"):showEditorLogin());
els["back-to-roles"].onclick=showRoleChoice;
els["editor-login-form"].onsubmit=async e=>{e.preventDefault();els["login-error"].textContent="Signing in...";const result=await authenticateEditor(els.username.value.trim(),els.password.value);if(result.ok)await showWorkspace("editor");else{els["login-error"].textContent=result.error||"Incorrect username or password.";els.password.select()}};
els["logout-button"].onclick=logout;els["add-task-button"].onclick=()=>openTaskModal();els["my-work-add"].onclick=()=>openTaskModal();els["backlog-add"].onclick=()=>openTaskModal();els["team-manage-button"].onclick=openTeamModal;els["activity-button"].onclick=()=>setView("activity");els["theme-toggle"].onclick=toggleTheme;
els["filter-button"].onclick=()=>els["filter-panel"].classList.toggle("hidden");
els["search-input"].oninput=e=>{state.search=e.target.value;renderBoard()};els["assignee-filter"].onchange=e=>{state.assignee=e.target.value;renderBoard()};els["priority-filter"].onchange=e=>{state.priority=e.target.value;renderBoard()};els["status-filter"].onchange=e=>{state.status=e.target.value;renderBoard()};els["sort-filter"].onchange=e=>{state.sort=e.target.value;renderBoard()};
els["clear-filters"].onclick=()=>{state.search="";state.assignee=state.priority=state.status="all";state.sort="default";els["search-input"].value="";els["assignee-filter"].value=els["priority-filter"].value=els["status-filter"].value="all";els["sort-filter"].value="default";renderBoard()};
els["task-form"].onsubmit=saveTaskFromForm;els["delete-task-button"].onclick=deleteCurrentTask;els["team-form"].onsubmit=saveMember;els["comment-form"].onsubmit=addCommentFromForm;
els["detail-edit-button"].onclick=()=>{const id=els["detail-edit-button"].dataset.id;closeModals();openTaskModal(id)};
els["export-button"].onclick=exportData;els["import-file"].onchange=e=>importData(e.target.files[0]);
document.querySelectorAll("[data-view]").forEach(n=>n.onclick=()=>setView(n.dataset.view));
document.querySelectorAll(".close-modal,.close-team-modal,.close-detail-modal,.close-activity-modal").forEach(b=>b.onclick=closeModals);
document.querySelectorAll(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModals();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"&&!els.workspace.classList.contains("hidden")){e.preventDefault();els["search-input"].focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="n"&&session.isEditor()){e.preventDefault();openTaskModal()}});
});
