const els={},state={search:"",assignee:"all",priority:"all",status:"all",sort:"default",view:"board"};
function cacheElements(){document.querySelectorAll("[id]").forEach(e=>els[e.id]=e)}
async async function showWorkspace(role){session.role=role;els["login-screen"].classList.add("hidden");els.workspace.classList.remove("hidden");const e=role==="editor";els["mode-label"].textContent=e?"Editor mode":"Guest mode";els["mode-description"].textContent=e?"Full access":"View only";els["user-label"].textContent=e?"Editor":"Guest";els["user-avatar"].textContent=e?"E":"G";els["team-manage-button"].classList.toggle("hidden",!e);applyTheme();await BackendSync.bootstrap();if(els["backend-status"])els["backend-status"].textContent=BackendSync.isConfigured()?"Cloud connected":"Local mode";renderAll()}
function showRoleChoice(){els["role-choice"].classList.remove("hidden");els["editor-login-form"].classList.add("hidden");els["login-error"].textContent=""}
function showEditorLogin(){els["role-choice"].classList.add("hidden");els["editor-login-form"].classList.remove("hidden");els.username.focus()}
async function logout(){await BackendSync.signOut();session.role=null;session.user=null;closeModals();els.workspace.classList.add("hidden");els["login-screen"].classList.remove("hidden");showRoleChoice()}
function renderAll(){renderSidebarTeam();populateAssigneeFilters();renderBoard();renderSummary();renderMyWork();renderBacklog();renderActivity();updateView()}
function renderSidebarTeam(){const t=getTeam();els["team-count"].textContent=t.length;els["sidebar-team-list"].innerHTML=t.slice(0,5).map(m=>`<div class="team-mini"><span class="avatar">${escapeHTML(initials(m.name))}</span><span>${escapeHTML(m.name)}</span></div>`).join("")}
function populateAssigneeFilters(){const v=state.assignee;els["assignee-filter"].innerHTML='<option value="all">Everyone</option>'+getTeam().map(m=>`<option value="${m.id}">${escapeHTML(m.name)}</option>`).join("");els["assignee-filter"].value=getTeam().some(m=>m.id===v)?v:"all"}
function getFilteredTasks(){const q=state.search.toLowerCase().trim();return getTasks().filter(t=>{const m=getMember(t.assigneeId),hay=[t.title,t.description,...(t.labels||[]),m?.name||""].join(" ").toLowerCase();return(!q||hay.includes(q))&&(state.assignee==="all"||t.assigneeId===state.assignee)&&(state.priority==="all"||t.priority===state.priority)&&(state.status==="all"||t.status===state.status)}).sort((a,b)=>compareTasks(a,b,state.sort))}
function renderBoard(){const tasks=getFilteredTasks();els.board.innerHTML=STATUS_COLUMNS.map(c=>{const list=tasks.filter(t=>t.status===c.id);return`<section class="board-column"><div class="column-head"><span class="column-title">${c.label}</span><span class="column-count">${list.length}</span></div><div class="task-list" data-status="${c.id}">${list.map(renderTaskCard).join("")}${!list.length?'<div class="guest-note">No matching tasks</div>':""}</div></section>`}).join("");document.querySelectorAll(".task-card").forEach(c=>{c.addEventListener("click",()=>openTaskDetail(c.dataset.id));if(session.isEditor()){c.draggable=true;c.addEventListener("dragstart",dragStart);c.addEventListener("dragend",dragEnd)}});if(session.isEditor())document.querySelectorAll(".task-list").forEach(l=>{l.addEventListener("dragover",dragOver);l.addEventListener("dragleave",e=>e.currentTarget.classList.remove("drag-over"));l.addEventListener("drop",drop)})}
function renderTaskCard(t){const m=getMember(t.assigneeId);return`<article class="task-card" data-id="${t.id}"><div class="task-top"><h4 class="task-title">${escapeHTML(t.title)}</h4><span class="priority ${t.priority}">${t.priority}</span></div>${t.description?`<p class="task-description">${escapeHTML(t.description)}</p>`:""}<div class="task-labels">${(t.labels||[]).map(l=>`<span class="task-label">${escapeHTML(l)}</span>`).join("")}</div><div class="task-bottom"><div class="assignee"><span class="avatar">${initials(m?.name||"U")}</span><span class="assignee-name">${escapeHTML(m?.name||"Unassigned")}</span></div><span class="due-date ${dueState(t.dueDate,t.status)}">${formatDueDate(t.dueDate)}</span></div></article>`}
function renderSummary(){const t=getTasks(),d=new Date();d.setHours(0,0,0,0);els["total-tasks"].textContent=t.length;els["progress-tasks"].textContent=t.filter(x=>x.status==="in-progress").length;els["completed-tasks"].textContent=t.filter(x=>x.status==="done").length;els["due-soon-tasks"].textContent=t.filter(x=>x.dueDate&&x.status!=="done"&&Math.round((new Date(x.dueDate+"T00:00:00")-d)/86400000)>=0&&Math.round((new Date(x.dueDate+"T00:00:00")-d)/86400000)<=3).length}
function renderMyWork(){const t=getTasks().filter(x=>x.assigneeId==="member-aman");els["my-total"].textContent=t.length;els["my-active"].textContent=t.filter(x=>["todo","in-progress"].includes(x.status)).length;els["my-review"].textContent=t.filter(x=>x.status==="in-review").length;els["my-done"].textContent=t.filter(x=>x.status==="done").length;els["my-work-list"].innerHTML=t.length?t.map(x=>`<button class="work-row" data-task-id="${x.id}"><span class="work-status ${x.status}"></span><span class="work-main"><strong>${escapeHTML(x.title)}</strong><small>${getStatusLabel(x.status)}</small></span><span class="priority ${x.priority}">${x.priority}</span><span class="due-date ${dueState(x.dueDate,x.status)}">${formatDueDate(x.dueDate)}</span></button>`).join(""):'<div class="empty-state"><strong>No work assigned</strong><span>Tasks assigned to Aman appear here.</span></div>';els["my-work-list"].querySelectorAll("[data-task-id]").forEach(b=>b.addEventListener("click",()=>openTaskDetail(b.dataset.taskId)))}
function renderBacklog(){const t=getTasks().filter(x=>x.status==="backlog");els["backlog-table-body"].innerHTML=t.length?t.map(x=>{const m=getMember(x.assigneeId);return`<tr data-task-id="${x.id}"><td><strong>${escapeHTML(x.title)}</strong><small>${escapeHTML(x.description||"No description")}</small></td><td>${escapeHTML(m?.name||"Unassigned")}</td><td><span class="priority ${x.priority}">${x.priority}</span></td><td class="${dueState(x.dueDate,x.status)}">${formatDueDate(x.dueDate)}</td><td>${(x.labels||[]).map(l=>`<span class="task-label">${escapeHTML(l)}</span>`).join(" ")}</td><td><button class="row-action">Open</button></td></tr>`}).join(""):'<tr><td colspan="6"><div class="empty-state"><strong>Backlog is clear</strong><span>No planned work is waiting.</span></div></td></tr>';els["backlog-table-body"].querySelectorAll("[data-task-id]").forEach(r=>r.addEventListener("click",()=>openTaskDetail(r.dataset.taskId)))}
function renderActivity(){const h=getActivity().slice(0,60).map(a=>`<div class="activity-row"><span class="activity-icon">${a.type==="team"?"◎":a.type==="status"?"↔":"✓"}</span><div><strong>${escapeHTML(a.message)}</strong><small>${relativeTime(a.timestamp)}</small></div></div>`).join("")||'<div class="empty-activity">No activity yet.</div>';els["activity-page-list"].innerHTML=h;els["activity-list"].innerHTML=h}
function relativeTime(s){const m=Math.floor(Math.max(0,Date.now()-new Date(s).getTime())/60000);return m<1?"just now":m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`}
function openTaskModal(id=null){if(!session.isEditor())return;const t=id?getTaskById(id):null;els["task-id"].value=t?.id||"";els["task-title"].value=t?.title||"";els["task-description"].value=t?.description||"";els["task-assignee"].innerHTML=getTeam().map(m=>`<option value="${m.id}">${escapeHTML(m.name)}</option>`).join("");els["task-assignee"].value=t?.assigneeId||getTeam()[0]?.id||"";els["task-status"].value=t?.status||"backlog";els["task-priority"].value=t?.priority||"medium";els["task-due-date"].value=t?.dueDate||"";els["task-labels"].value=(t?.labels||[]).join(", ");els["task-modal-title"].textContent=t?"Edit task":"Create task";els["delete-task-button"].classList.toggle("hidden",!t);showModal(els["task-modal"])}
function openTaskDetail(id){const t=getTaskById(id);if(!t)return;const m=getMember(t.assigneeId);els["detail-title"].textContent=t.title;els["detail-description"].textContent=t.description||"No description provided.";els["detail-assignee"].textContent=m?.name||"Unassigned";els["detail-status"].textContent=getStatusLabel(t.status);els["detail-priority"].textContent=t.priority;els["detail-due"].textContent=formatDueDate(t.dueDate);els["detail-labels"].innerHTML=(t.labels||[]).map(l=>`<span class="task-label">${escapeHTML(l)}</span>`).join("")||"No labels";els["detail-edit-button"].classList.toggle("hidden",!session.isEditor());els["detail-edit-button"].dataset.id=id;els["comment-input"].value="";renderComments(id);renderHistory(t);showModal(els["task-detail-modal"])}
function renderComments(id){const c=getComments()[id]||[];els["task-comments"].innerHTML=c.length?c.map(x=>`<div class="comment"><div class="comment-meta"><strong>${escapeHTML(x.author)}</strong><small>${relativeTime(x.timestamp)}</small></div><p>${escapeHTML(x.text)}</p></div>`).join(""):'<div class="empty-comments">No comments yet.</div>'}
function renderHistory(t){const h=t.history||[];els["task-history"].innerHTML=h.length?h.slice(0,20).map(x=>`<div class="history-row"><span></span><div><strong>${escapeHTML(x.action)}</strong><small>${escapeHTML(x.details||"")} · ${relativeTime(x.timestamp)}</small></div></div>`).join(""):'<div class="empty-comments">No recorded changes yet.</div>'}
function saveTaskFromForm(e){e.preventDefault();if(!session.isEditor())return;const id=els["task-id"].value||makeTaskId(),old=getTaskById(id),t={id,title:els["task-title"].value.trim(),description:els["task-description"].value.trim(),assigneeId:els["task-assignee"].value,status:els["task-status"].value,priority:els["task-priority"].value,dueDate:els["task-due-date"].value,labels:els["task-labels"].value.split(",").map(x=>x.trim()).filter(Boolean),createdAt:old?.createdAt||new Date().toISOString(),history:old?.history||[]};if(old&&old.status!==t.status)addTaskHistory(t,"Status changed",`${getStatusLabel(old.status)} → ${getStatusLabel(t.status)}`);if(old&&old.assigneeId!==t.assigneeId)addTaskHistory(t,"Assignee changed",`${getMember(old.assigneeId)?.name||"Unassigned"} → ${getMember(t.assigneeId)?.name||"Unassigned"}`);if(old&&old.priority!==t.priority)addTaskHistory(t,"Priority changed",`${old.priority} → ${t.priority}`);if(old&&old.dueDate!==t.dueDate)addTaskHistory(t,"Due date changed",`${formatDueDate(old.dueDate)} → ${formatDueDate(t.dueDate)}`);if(!old)addTaskHistory(t,"Task created");upsertTask(t);addActivity("task",old?`"${t.title}" was updated`:`"${t.title}" was created`,{taskId:id});closeModals();renderAll();showToast(old?"Task updated":"Task created")}
function deleteCurrentTask(){const id=els["task-id"].value,t=getTaskById(id);if(!t||!confirm(`Delete "${t.title}"?`))return;removeTask(id);addActivity("task",`"${t.title}" was deleted`,{taskId:id});closeModals();renderAll();showToast("Task deleted")}
function openTeamModal(){if(!session.isEditor())return;renderTeamManager();showModal(els["team-modal"])}
function renderTeamManager(){els["team-manager-list"].innerHTML=getTeam().map(m=>`<div class="team-manager-row"><div class="team-manager-person"><span class="avatar">${initials(m.name)}</span><div><strong>${escapeHTML(m.name)}</strong><small>${escapeHTML(m.role)}</small></div></div><button class="remove-member" data-id="${m.id}">Remove</button></div>`).join("");els["team-manager-list"].querySelectorAll(".remove-member").forEach(b=>b.onclick=()=>{const r=removeMember(b.dataset.id);if(!r.success){showToast(r.reason==="assigned"?"Reassign tasks first":"Keep at least one member");return}renderAll();renderTeamManager();showToast("Team member removed")})}
function saveMember(e){e.preventDefault();if(!session.isEditor())return;const n=els["member-name"].value.trim();if(!n)return;addMember(n,els["member-role"].value);els["member-name"].value="";els["member-role"].value="";renderAll();renderTeamManager();showToast("Team member added")}
function addCommentFromForm(e){e.preventDefault();if(!session.isEditor())return;const text=els["comment-input"].value.trim(),id=els["detail-edit-button"].dataset.id;if(!text)return;addComment(id,"Editor",text);const t=getTaskById(id);addTaskHistory(t,"Comment added",text.slice(0,80));upsertTask(t);addActivity("task",`Comment added to "${t.title}"`,{taskId:id});renderComments(id);renderHistory(t);renderActivity();els["comment-input"].value="";showToast("Comment added")}
function showModal(m){m.classList.remove("hidden");m.setAttribute("aria-hidden","false")}
function closeModals(){document.querySelectorAll(".modal-backdrop").forEach(m=>{m.classList.add("hidden");m.setAttribute("aria-hidden","true")})}
let draggedTaskId=null;function dragStart(e){draggedTaskId=e.currentTarget.dataset.id;e.currentTarget.classList.add("dragging");e.dataTransfer.effectAllowed="move"}function dragEnd(e){e.currentTarget.classList.remove("dragging");document.querySelectorAll(".task-list").forEach(x=>x.classList.remove("drag-over"));draggedTaskId=null}function dragOver(e){e.preventDefault();e.currentTarget.classList.add("drag-over")}function drop(e){e.preventDefault();e.currentTarget.classList.remove("drag-over");if(draggedTaskId&&moveTask(draggedTaskId,e.currentTarget.dataset.status)){renderAll();showToast("Task moved")}}
function setView(v){state.view=v;updateView()}
function updateView(){document.querySelectorAll(".app-view").forEach(v=>v.classList.add("hidden"));document.getElementById("view-"+state.view).classList.remove("hidden");document.querySelectorAll(".nav-item[data-view]").forEach(n=>n.classList.toggle("active",n.dataset.view===state.view))}
function applyTheme(){const p=getPreferences();document.documentElement.dataset.theme=p.theme;els["theme-toggle"].textContent=p.theme==="dark"?"☀":"◐"}
function toggleTheme(){const p=getPreferences();p.theme=p.theme==="dark"?"light":"dark";savePreferences(p);applyTheme()}
function exportData(){const b=new Blob([JSON.stringify({version:3,tasks:getTasks(),team:getTeam(),activity:getActivity(),comments:getComments()},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="re-task-backup.json";a.click();URL.revokeObjectURL(u);showToast("Backup exported")}
function importData(f){if(!f||!session.isEditor())return;const r=new FileReader();r.onload=e=>{try{const p=JSON.parse(e.target.result);if(!Array.isArray(p.tasks)||!Array.isArray(p.team))throw 0;saveTasks(p.tasks);saveTeam(p.team);saveActivity(p.activity||[]);saveComments(p.comments||{});renderAll();showToast("Backup imported")}catch{showToast("Invalid backup")}els["import-file"].value=""};r.readAsText(f)}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
let toastTimer;function showToast(m){clearTimeout(toastTimer);els.toast.textContent=m;els.toast.classList.add("show");toastTimer=setTimeout(()=>els.toast.classList.remove("show"),1800)}

window.renderAll=renderAll;

window.renderAll=renderAll;
